name: iqra_islamic_app
description: A complete Islamic Wisdom App including Quran, Hadith, and Fatawa sections.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  fluttertoast: ^8.2.4
  connectivity_plus: ^6.1.0
  path_provider: ^2.1.2
  webview_flutter: ^4.7.0
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.1
  share_plus: ^10.0.2
  sqflite: ^2.4.0
  get: ^4.6.6
  audio_players: ^1.2.0

  # ✅ Correct Quran package (available version)
  quran: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/quran/
    - assets/images/
    - assets/audio/
    - assets/json/

  fonts:
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
